import { Order } from "@/components/shop/orders/types";

export const initialOrders: Order[] = [
  {
    id: "order-5",
    code: "#0005",
    ref: "ORD-20260516-B0F2",
    customerName: "ญัฐพล",
    category: "ถ่ายเอกสารขาว-ดำ",
    paperSize: "A4",
    copies: 3,
    totalPages: 75,
    addOns: ["เข้าเล่ม", "เคลือบ"],
    file: { name: "งาน_ญัฐพล.pdf", sizeLabel: "2.4 MB", type: "pdf" },
    paymentSlip: { name: "สลิป_0005.jpg", sizeLabel: "312 KB", type: "image" },
    delivery: {
      method: "shop_delivery",
      address: "หอพัก UP Dorm ชั้น 3 ห้อง 305 เลขที่ 99/15 ถ.พหลโยธิน ต.แม่กา อ.เมือง จ.พะเยา 56000",
    },
    price: 120,
    status: "pending_review",
    createdAtLabel: "16 พ.ค. 10:30",
    note: "ช่วยเข้าเล่มให้แน่นหน่อยนะคะ จะใช้ส่งอาจารย์",
  },
  {
    id: "order-4",
    code: "#0004",
    ref: "ORD-20260516-9C41",
    customerName: "วสิ",
    category: "เคลือบ",
    paperSize: "A4",
    copies: 1,
    totalPages: 1,
    addOns: ["เคลือบด้าน"],
    file: { name: "งาน_วสิ.jpg", sizeLabel: "1.8 MB", type: "image" },
    paymentSlip: { name: "สลิป_0004.jpg", sizeLabel: "245 KB", type: "image" },
    delivery: { method: "self_pickup" },
    price: 35,
    status: "pending_review",
    createdAtLabel: "16 พ.ค. 09:45",
  },
  {
    id: "order-3",
    code: "#0003",
    ref: "ORD-20260516-4D77",
    customerName: "ปาณิชา",
    category: "ถ่ายเอกสารขาว-ดำ",
    paperSize: "A4",
    copies: 2,
    totalPages: 40,
    addOns: [],
    file: { name: "งาน_ปาณิชา.pdf", sizeLabel: "1.2 MB", type: "pdf" },
    paymentSlip: { name: "สลิป_0003.jpg", sizeLabel: "198 KB", type: "image" },
    delivery: {
      method: "shop_delivery",
      address: "หอพักอินฟินิต ชั้น 4 ห้อง 410 เลขที่ 22/8 ถ.มหาวิทยาลัย ต.แม่กา อ.เมือง จ.พะเยา 56000",
    },
    price: 15,
    status: "pending_review",
    createdAtLabel: "16 พ.ค. 09:30",
    note: "รบกวนพิมพ์หน้า-หลังด้วยค่ะ ไม่งั้นกระดาษไม่พอ",
  },
  {
    id: "order-2",
    code: "#0002",
    ref: "ORD-20260516-77A0",
    customerName: "เมย์",
    category: "เข้าเล่ม",
    paperSize: "A4",
    copies: 1,
    totalPages: 1,
    addOns: ["เข้าเล่มรายงาน"],
    file: { name: "งาน_เมย์.pdf", sizeLabel: "3.1 MB", type: "pdf" },
    paymentSlip: { name: "สลิป_0002.jpg", sizeLabel: "210 KB", type: "image" },
    delivery: { method: "self_pickup" },
    price: 40,
    status: "pending_review",
    createdAtLabel: "16 พ.ค. 09:20",
  },
  {
    id: "order-1",
    code: "#0001",
    ref: "ORD-20260516-1E33",
    customerName: "วรเมธ",
    category: "ถ่ายเอกสารสี",
    paperSize: "A4",
    copies: 5,
    totalPages: 20,
    addOns: ["เข้าเล่ม", "เคลือบ"],
    file: { name: "งาน_วรเมธ.pdf", sizeLabel: "2.7 MB", type: "pdf" },
    paymentSlip: { name: "สลิป_0001.jpg", sizeLabel: "280 KB", type: "image" },
    delivery: {
      method: "shop_delivery",
      address: "หอพักแบมบู ชั้น 1 ห้อง 105 เลขที่ 45/3 ถ.พหลโยธิน ต.แม่กา อ.เมือง จ.พะเยา 56000",
    },
    price: 250,
    status: "pending_review",
    createdAtLabel: "16 พ.ค. 08:50",
  },
  {
    id: "order-6",
    code: "#0006",
    ref: "ORD-20260514-D8A2",
    customerName: "พิมพ์ใจ",
    category: "พิมพ์โปสเตอร์",
    paperSize: "A3",
    copies: 1,
    totalPages: 2,
    addOns: [],
    file: { name: "poster_final.jpg", sizeLabel: "4.5 MB", type: "image" },
    paymentSlip: { name: "สลิป_0006.jpg", sizeLabel: "265 KB", type: "image" },
    delivery: {
      method: "shop_delivery",
      address: "หอพักดอกบัว ชั้น 2 ห้อง 203 เลขที่ 12/7 ถ.มหาวิทยาลัย ต.แม่กา อ.เมือง จ.พะเยา 56000",
    },
    price: 90,
    status: "pending_review",
    createdAtLabel: "14 พ.ค. 15:40",
  },
];
