import { MainService, AddOnService, DeliveryOption } from "@/components/shop/services/types";

export const initialAddOnServices: AddOnService[] = [
  {
    id: "addon-1",
    name: "เข้าเล่มสันกาว",
    description: "เข้าเล่มไส้กาวความร้อน แน่นหนา ทนทาน",
    price: 45,
    unit: "เล่ม",
    estimatedTime: "10 นาที",
    isActive: true,
  },
  {
    id: "addon-2",
    name: "เข้าเล่มสันห่วง",
    description: "เข้าเล่มสันห่วงพลาสติก เปิดกางง่าย",
    price: 60,
    unit: "เล่ม",
    estimatedTime: "10 นาที",
    isActive: true,
  },
  {
    id: "addon-3",
    name: "เคลือบบัตร",
    description: "เคลือบพลาสติกแข็งสำหรับบัตรหรือการ์ด",
    price: 30,
    unit: "แผ่น",
    estimatedTime: "5 นาที",
    isActive: true,
  },
  {
    id: "addon-4",
    name: "เคลือบเอกสาร",
    description: "เคลือบพลาสติกร้อนกันน้ำ กันรอยขีดข่วน",
    price: 20,
    unit: "แผ่น",
    estimatedTime: "5 นาที",
    isActive: true,
  },
  {
    id: "addon-5",
    name: "ปกใส",
    description: "แผ่นใสรองปกหน้า-หลัง เพิ่มความสวยงาม",
    price: 10,
    unit: "ชิ้น",
    estimatedTime: "2 นาที",
    isActive: true,
  },
];

export const initialMainServices: MainService[] = [
  {
    id: "main-1",
    name: "ถ่ายเอกสาร",
    description: "ถ่ายเอกสารขาวดำทั่วไป ความคมชัดสูง",
    paperSizes: ["A4"],
    colors: ["ขาวดำ"],
    price: 1,
    unit: "แผ่น",
    estimatedTime: "5 นาที",
    availableAddOns: [
      { addOnId: "addon-1", extraPrice: 45 },
      { addOnId: "addon-2", extraPrice: 60 },
      { addOnId: "addon-5", extraPrice: 10 },
    ],
    isActive: true,
  },
  {
    id: "main-2",
    name: "พิมพ์เอกสาร",
    description: "พิมพ์เอกสารสี ละเอียด คมชัด",
    paperSizes: ["A4"],
    colors: ["สี"],
    price: 8,
    unit: "แผ่น",
    estimatedTime: "5 นาที",
    availableAddOns: [
      { addOnId: "addon-1", extraPrice: 45 },
      { addOnId: "addon-4", extraPrice: 20 },
      { addOnId: "addon-5", extraPrice: 10 },
    ],
    isActive: true,
  },
  {
    id: "main-3",
    name: "พิมพ์โปสเตอร์",
    description: "พิมพ์โปสเตอร์คุณภาพสูง ภาพสดใส",
    paperSizes: ["A3"],
    colors: ["สี"],
    price: 80,
    unit: "แผ่น",
    estimatedTime: "30 นาที",
    availableAddOns: [
      { addOnId: "addon-4", extraPrice: 25 },
    ],
    isActive: true,
  },
  {
    id: "main-4",
    name: "สแกนเอกสาร",
    description: "สแกนแปลงไฟล์เป็น PDF / JPG ความละเอียดสูง",
    paperSizes: ["A4"],
    colors: ["สี"],
    price: 5,
    unit: "หน้า",
    estimatedTime: "5 นาที",
    availableAddOns: [],
    isActive: true,
  },
  {
    id: "main-5",
    name: "พิมพ์แบบแปลน",
    description: "พิมพ์แบบแปลนทางวิศวกรรม/สถาปัตยกรรม",
    paperSizes: ["A3"],
    colors: ["ขาวดำ"],
    price: 20,
    unit: "แผ่น",
    estimatedTime: "15 นาที",
    availableAddOns: [],
    isActive: true,
  },
];

export const initialDeliveryOptions: DeliveryOption[] = [
  {
    id: "delivery-1",
    name: "รับหน้าร้าน",
    description: "มารับสินค้าที่ร้านด้วยตนเอง ไม่คิดค่าจัดส่ง",
    baseFee: 0,
    isActive: true,
  },
  {
    id: "delivery-2",
    name: "Kerry Express",
    description: "จัดส่งด่วนทั่วประเทศ รับสินค้าภายใน 1-2 วัน",
    baseFee: 40,
    freeShippingThreshold: 500,
    isActive: true,
  },
  {
    id: "delivery-3",
    name: "Flash Express",
    description: "บริการขนส่งด่วน พัสดุถึงมือรวดเร็ว",
    baseFee: 35,
    freeShippingThreshold: 500,
    isActive: true,
  },
  {
    id: "delivery-4",
    name: "EMS พัสดุไปรษณีย์ไทย",
    description: "จัดส่งด่วน EMS โดยไปรษณีย์ไทย",
    baseFee: 50,
    freeShippingThreshold: 1000,
    isActive: true,
  },
];
